import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { recolourLocal, computeGarmentBrightnessRange } from "./recolourLocal";

/**
 * Parity test: assert recolourLocal matches the Python pipeline's output
 * within a perceptual tolerance.
 *
 * Two failure modes this catches:
 *  - JS port drift: someone changes recolourLocal.ts and the math diverges
 *    from core/garment_recolor.py's apply_colors. Test A fails.
 *  - Cross-path drift: the sample flow (precomputed brightness range from
 *    static metadata) and the upload flow (range computed client-side from
 *    image + mask) must produce equivalent output for equivalent inputs.
 *    Test B fails if they diverge.
 *
 * Fixture is generated by scripts/generate_parity_fixture.py. Re-run that
 * script when the algorithm in either Python or the JS port changes.
 *
 * Threshold rationale: spike validation in scripts/spike_hsv showed mean
 * abs RGB diff of 2-3 / 255 across realistic palettes. We assert mean
 * abs RGB diff < 6 / 255 (small margin above spike) and max < 50 / 255
 * (catches outlier divergence at brightness-band boundaries from sort
 * stability differences between numpy and JS). Below these, human eyes
 * cannot distinguish the two outputs. Using mean-abs (not RMSE) so the
 * threshold maps directly onto the spike's published numbers.
 */

const FIXTURE_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "__fixtures__",
  "parity",
);

interface Meta {
  label: string;
  width: number;
  height: number;
  palette: string[];
  percentages: number[];
  brightnessRange: { minV: number; maxV: number };
}

function loadFixture() {
  const meta = JSON.parse(
    readFileSync(join(FIXTURE_DIR, "meta.json"), "utf8"),
  ) as Meta;
  const inputBuf = readFileSync(join(FIXTURE_DIR, "input-rgba.bin"));
  const maskBuf = readFileSync(join(FIXTURE_DIR, "mask.bin"));
  const expectedBuf = readFileSync(join(FIXTURE_DIR, "expected-rgba.bin"));
  return {
    meta,
    input: new Uint8ClampedArray(
      inputBuf.buffer,
      inputBuf.byteOffset,
      inputBuf.byteLength,
    ),
    mask: new Uint8Array(maskBuf),
    expected: new Uint8ClampedArray(
      expectedBuf.buffer,
      expectedBuf.byteOffset,
      expectedBuf.byteLength,
    ),
  };
}

/**
 * Mean abs RGB diff and max abs diff over foreground pixels. Background
 * pixels are excluded because the recolour algorithm leaves them
 * unchanged. Mean-abs (not RMSE) so the threshold maps onto the spike's
 * "mean abs diff 2-3 / 255" headline number.
 */
function rgbDiff(
  actual: Uint8ClampedArray,
  expected: Uint8ClampedArray,
  mask: Uint8Array,
): { mean: number; max: number; pixelsCounted: number } {
  let totalAbs = 0;
  let maxAbs = 0;
  let count = 0;
  for (let i = 0; i < mask.length; i++) {
    if (mask[i] < 128) continue;
    const px = i * 4;
    const dr = Math.abs(actual[px] - expected[px]);
    const dg = Math.abs(actual[px + 1] - expected[px + 1]);
    const db = Math.abs(actual[px + 2] - expected[px + 2]);
    const avg = (dr + dg + db) / 3;
    totalAbs += avg;
    if (avg > maxAbs) maxAbs = avg;
    count++;
  }
  return {
    mean: count > 0 ? totalAbs / count : 0,
    max: maxAbs,
    pixelsCounted: count,
  };
}

describe("recolourLocal parity vs Python reference", () => {
  it("Test A: matches Python output when given an explicit precomputedRange (sample/static path)", () => {
    const { meta, input, mask, expected } = loadFixture();
    const buffer = new Uint8ClampedArray(input);

    recolourLocal(
      buffer,
      mask,
      meta.width,
      meta.height,
      meta.palette,
      meta.percentages,
      meta.brightnessRange,
    );

    const { mean, max, pixelsCounted } = rgbDiff(buffer, expected, mask);
    expect(pixelsCounted).toBeGreaterThan(0);
    expect(mean).toBeLessThan(6);
    expect(max).toBeLessThan(50);
  });

  it("Test B: matches Python output computing brightness range from scratch (upload path)", () => {
    const { meta, input, mask, expected } = loadFixture();

    // First leg of Test B: JS-computed range must match Python-computed
    // range for the same pixels. If this fails, the upload flow's
    // normalisation drifts from the sample flow's normalisation.
    const computedRange = computeGarmentBrightnessRange(
      input,
      mask,
      meta.width,
      meta.height,
    );
    expect(Math.abs(computedRange.minV - meta.brightnessRange.minV)).toBeLessThan(2);
    expect(Math.abs(computedRange.maxV - meta.brightnessRange.maxV)).toBeLessThan(2);

    // Second leg: run recolour without an explicit range; the function
    // computes its own internally. Compare to Python expected.
    const buffer = new Uint8ClampedArray(input);
    recolourLocal(
      buffer,
      mask,
      meta.width,
      meta.height,
      meta.palette,
      meta.percentages,
      null,
    );

    const { mean, max, pixelsCounted } = rgbDiff(buffer, expected, mask);
    expect(pixelsCounted).toBeGreaterThan(0);
    expect(mean).toBeLessThan(6);
    expect(max).toBeLessThan(50);
  });
});
